spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hinernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
  instance:
    prefer-ip-address: true
---
spring:
  profiles: peer1

server:
  port: 8000
---
spring:
  profiles: peer2

server:
  port: 8001
