server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
  instance:
    prefer-ip-address: true